#mysql
#diver_name=com.mysql.jdbc.Driver
#url=jdbc:mysql://localhost:3306/hanwei?useUnicode=true&characterEncoding=UTF-8
#username=sa
#password=hanwei2018
#database_name=DB_JAVA_CODE

#oracle
#diver_name=oracle.jdbc.driver.OracleDriver
#url=jdbc:oracle:thin:@192.168.1.200:1521:ORCL
#username=scott
#password=tiger
#database_name=ORCL

#postgre
diver_name=org.postgresql.Driver
url=jdbc:postgresql://10.0.15.28:5432/workorder_center
username=postgres
password=Data@2025
database_name=workorder_center


#diver_name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#url=jdbc:sqlserver://172.20.108.19:1433;DatabaseName=DB_RIVER_MONITORING
#username=syssql
#password=Data@2024


#diver_name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#url=jdbc:sqlserver://10.30.100.141:1433;DatabaseName=DB_RIVER_MONITORING
#username=syssql
#password=Data@2024

#diver_name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#url=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=DB_RIVER_MONITORING
#username=sa
#password=123456
